In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr[0]

np.int64(1)

# Array Creation

In [9]:
listar = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [10]:
listar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listar.dtype

dtype('int64')

In [12]:
listar.size

9

In [13]:
listar.shape

(3, 3)

# Intrinsic Method of Array Creation

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.shape

(2, 5)

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace = np.linspace(1, 50, 10)

In [20]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [21]:
emp = np.empty((4,6))

In [22]:
emp

array([[ 0.0000000e+000,  0.0000000e+000,  0.0000000e+000,
         0.0000000e+000,  0.0000000e+000,  0.0000000e+000],
       [ 0.0000000e+000, -2.0100246e-310,  0.0000000e+000,
         0.0000000e+000,  0.0000000e+000,  0.0000000e+000],
       [ 0.0000000e+000,  0.0000000e+000,  0.0000000e+000,
         0.0000000e+000,  0.0000000e+000,  0.0000000e+000],
       [ 0.0000000e+000,  0.0000000e+000,  0.0000000e+000,
         0.0000000e+000,  0.0000000e+000,  0.0000000e+000]])

In [23]:
ide = np.identity(45)

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

# AXIS

In [25]:
ar1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [26]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
ar1.sum(axis = 0)

array([12, 15, 18])

In [28]:
ar1.sum(axis = 1)

array([ 6, 15, 24])

In [29]:
ar1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [30]:
ar1.ndim

2

In [31]:
ar1.size

9

In [32]:
arr.nbytes

32

*** 1D Array ***

In [33]:
one = np.array([1,2,3,5])

In [34]:
one.argmax()

np.int64(3)

In [35]:
one.argmin()

np.int64(0)

In [36]:
one.argsort()

array([0, 1, 2, 3])

# Mathmatical Opperations

In [37]:
ar2 = np.array([[1,2,3],
                   [4,6,6],
                   [7,0,9]])

In [38]:
ar2

array([[1, 2, 3],
       [4, 6, 6],
       [7, 0, 9]])

In [39]:
ar1 + ar2

array([[ 2,  4,  6],
       [ 8, 11, 12],
       [14,  8, 18]])

In [40]:
ar1 * ar2

array([[ 1,  4,  9],
       [16, 30, 36],
       [49,  0, 81]])

In [41]:
ar1.sum()

np.int64(45)

In [42]:
ar2.sum()

np.int64(38)

In [43]:
np.count_nonzero(ar1)

np.int64(9)

In [44]:
np.where(ar2 < 2)

(array([0, 2]), array([0, 1]))